// Generated by CIRCT firtool-1.44.0
module selector(	// @[<stdin>:3:10]
  input  [1:0] x0,	// @[lab1/src/top.scala:22:14]
               x1,	// @[lab1/src/top.scala:22:14]
               x2,	// @[lab1/src/top.scala:22:14]
               x3,	// @[lab1/src/top.scala:22:14]
               sel,	// @[lab1/src/top.scala:22:14]
  output [1:0] out	// @[lab1/src/top.scala:22:14]
);

  reg [1:0] casez_tmp;	// @[lab1/src/top.scala:31:24, :32:12, :33:30]
  always_comb begin	// @[lab1/src/top.scala:31:{15,24}, :32:12, :33:{21,30}, :34:12, :35:{21,30}, :36:12, :37:{21,30}, :38:12, :40:12]
    casez (sel)	// @[lab1/src/top.scala:31:{15,24}, :32:12, :33:{21,30}, :34:12, :35:{21,30}, :36:12, :37:{21,30}, :38:12, :40:12]
      2'b00:
        casez_tmp = x0;	// @[lab1/src/top.scala:31:{15,24}, :32:12, :33:{21,30}, :34:12, :35:{21,30}, :36:12, :37:{21,30}, :38:12, :40:12]
      2'b01:
        casez_tmp = x1;	// @[lab1/src/top.scala:31:{15,24}, :32:12, :33:{21,30}, :34:12, :35:{21,30}, :36:12, :37:{21,30}, :38:12, :40:12]
      2'b10:
        casez_tmp = x2;	// @[lab1/src/top.scala:31:{15,24}, :32:12, :33:{21,30}, :34:12, :35:{21,30}, :36:12, :37:{21,30}, :38:12, :40:12]
      default:
        casez_tmp = x3;	// @[lab1/src/top.scala:31:{15,24}, :32:12, :33:{21,30}, :34:12, :35:{21,30}, :36:12, :37:{21,30}, :38:12, :40:12]
    endcase	// @[lab1/src/top.scala:31:{15,24}, :32:12, :33:{21,30}, :34:12, :35:{21,30}, :36:12, :37:{21,30}, :38:12, :40:12]
  end // always_comb
  assign out = casez_tmp;	// @[<stdin>:3:10, lab1/src/top.scala:31:24, :32:12, :33:30]
endmodule

module top(	// @[<stdin>:27:10]
  input        clock,	// @[<stdin>:28:11]
               reset,	// @[<stdin>:29:11]
  input  [9:0] sw,	// @[lab1/src/top.scala:4:14]
  output [1:0] led	// @[lab1/src/top.scala:4:14]
);

  selector selector (	// @[lab1/src/top.scala:12:24]
    .x0  (sw[3:2]),	// @[lab1/src/top.scala:14:26]
    .x1  (sw[5:4]),	// @[lab1/src/top.scala:15:26]
    .x2  (sw[7:6]),	// @[lab1/src/top.scala:16:26]
    .x3  (sw[9:8]),	// @[lab1/src/top.scala:17:26]
    .sel (sw[1:0]),	// @[lab1/src/top.scala:13:27]
    .out (led)
  );
endmodule

