// Generated by CIRCT firtool-1.44.0
module selector(	// @[<stdin>:3:10]
  input  [1:0] in_0,	// @[lab1/src/top.scala:21:14]
               in_1,	// @[lab1/src/top.scala:21:14]
               in_2,	// @[lab1/src/top.scala:21:14]
               in_3,	// @[lab1/src/top.scala:21:14]
               in_4,	// @[lab1/src/top.scala:21:14]
  output [1:0] out	// @[lab1/src/top.scala:21:14]
);

  reg [1:0] casez_tmp;	// @[src/main/scala/chisel3/util/Mux.scala:141:16]
  always_comb begin	// @[lab1/src/top.scala:27:15, :28:15, :29:15, :30:15, src/main/scala/chisel3/util/Mux.scala:141:16]
    casez (in_4)	// @[lab1/src/top.scala:27:15, :28:15, :29:15, :30:15, src/main/scala/chisel3/util/Mux.scala:141:16]
      2'b00:
        casez_tmp = in_0;	// @[lab1/src/top.scala:27:15, :28:15, :29:15, :30:15, src/main/scala/chisel3/util/Mux.scala:141:16]
      2'b01:
        casez_tmp = in_1;	// @[lab1/src/top.scala:27:15, :28:15, :29:15, :30:15, src/main/scala/chisel3/util/Mux.scala:141:16]
      2'b10:
        casez_tmp = in_2;	// @[lab1/src/top.scala:27:15, :28:15, :29:15, :30:15, src/main/scala/chisel3/util/Mux.scala:141:16]
      default:
        casez_tmp = in_3;	// @[lab1/src/top.scala:27:15, :28:15, :29:15, :30:15, src/main/scala/chisel3/util/Mux.scala:141:16]
    endcase	// @[lab1/src/top.scala:27:15, :28:15, :29:15, :30:15, src/main/scala/chisel3/util/Mux.scala:141:16]
  end // always_comb
  assign out = casez_tmp;	// @[<stdin>:3:10, src/main/scala/chisel3/util/Mux.scala:141:16]
endmodule

module top(	// @[<stdin>:18:10]
  input        clock,	// @[<stdin>:19:11]
               reset,	// @[<stdin>:20:11]
  input  [9:0] sw,	// @[lab1/src/top.scala:5:14]
  output [1:0] led	// @[lab1/src/top.scala:5:14]
);

  selector selector (	// @[lab1/src/top.scala:10:24]
    .in_0 (sw[3:2]),	// @[lab1/src/top.scala:11:29]
    .in_1 (sw[5:4]),	// @[lab1/src/top.scala:12:29]
    .in_2 (sw[7:6]),	// @[lab1/src/top.scala:13:29]
    .in_3 (sw[9:8]),	// @[lab1/src/top.scala:14:29]
    .in_4 (sw[1:0]),	// @[lab1/src/top.scala:16:29]
    .out  (led)
  );
endmodule

