// Generated by CIRCT firtool-1.44.0
module Seg(	// @[<stdin>:3:10]
  input        enable,	// @[lab2/src/top.scala:42:14]
  input  [2:0] seg_in,	// @[lab2/src/top.scala:42:14]
  output [7:0] seg_out	// @[lab2/src/top.scala:42:14]
);

  reg [7:0] casez_tmp;	// @[src/main/scala/chisel3/util/Mux.scala:141:16]
  always_comb begin	// @[lab2/src/top.scala:53:20, :54:20, :55:20, :56:20, :57:20, :58:20, :59:20, :60:20, src/main/scala/chisel3/util/Mux.scala:141:16]
    casez (seg_in)	// @[lab2/src/top.scala:53:20, :54:20, :55:20, :56:20, :57:20, :58:20, :59:20, :60:20, src/main/scala/chisel3/util/Mux.scala:141:16]
      3'b000:
        casez_tmp = 8'hFD;	// @[lab2/src/top.scala:53:20, :54:20, :55:20, :56:20, :57:20, :58:20, :59:20, :60:20, src/main/scala/chisel3/util/Mux.scala:141:16]
      3'b001:
        casez_tmp = 8'h60;	// @[lab2/src/top.scala:53:20, :54:20, :55:20, :56:20, :57:20, :58:20, :59:20, :60:20, src/main/scala/chisel3/util/Mux.scala:141:16]
      3'b010:
        casez_tmp = 8'hDA;	// @[lab2/src/top.scala:53:20, :54:20, :55:20, :56:20, :57:20, :58:20, :59:20, :60:20, src/main/scala/chisel3/util/Mux.scala:141:16]
      3'b011:
        casez_tmp = 8'hF2;	// @[lab2/src/top.scala:53:20, :54:20, :55:20, :56:20, :57:20, :58:20, :59:20, :60:20, src/main/scala/chisel3/util/Mux.scala:141:16]
      3'b100:
        casez_tmp = 8'h66;	// @[lab2/src/top.scala:53:20, :54:20, :55:20, :56:20, :57:20, :58:20, :59:20, :60:20, src/main/scala/chisel3/util/Mux.scala:141:16]
      3'b101:
        casez_tmp = 8'hB6;	// @[lab2/src/top.scala:53:20, :54:20, :55:20, :56:20, :57:20, :58:20, :59:20, :60:20, src/main/scala/chisel3/util/Mux.scala:141:16]
      3'b110:
        casez_tmp = 8'hBE;	// @[lab2/src/top.scala:53:20, :54:20, :55:20, :56:20, :57:20, :58:20, :59:20, :60:20, src/main/scala/chisel3/util/Mux.scala:141:16]
      default:
        casez_tmp = 8'hE0;	// @[lab2/src/top.scala:53:20, :54:20, :55:20, :56:20, :57:20, :58:20, :59:20, :60:20, src/main/scala/chisel3/util/Mux.scala:141:16]
    endcase	// @[lab2/src/top.scala:53:20, :54:20, :55:20, :56:20, :57:20, :58:20, :59:20, :60:20, src/main/scala/chisel3/util/Mux.scala:141:16]
  end // always_comb
  assign seg_out = ~({8{enable}} & casez_tmp);	// @[<stdin>:3:10, lab2/src/top.scala:48:20, src/main/scala/chisel3/util/Mux.scala:141:16]
endmodule

module top(	// @[<stdin>:29:10]
  input        clock,	// @[<stdin>:30:11]
               reset,	// @[<stdin>:31:11]
  input  [8:0] sw,	// @[lab2/src/top.scala:5:14]
  output       ledr_0,	// @[lab2/src/top.scala:5:14]
               ledr_1,	// @[lab2/src/top.scala:5:14]
               ledr_2,	// @[lab2/src/top.scala:5:14]
               ledr_3,	// @[lab2/src/top.scala:5:14]
  output [7:0] seg0	// @[lab2/src/top.scala:5:14]
);

  wire [2:0] hotvalue =
    sw[7:0] == 8'h0 | sw[0]
      ? 3'h0
      : sw[1]
          ? 3'h1
          : sw[2]
              ? 3'h2
              : sw[3] ? 3'h3 : sw[4] ? 3'h4 : sw[5] ? 3'h5 : {2'h3, ~(sw[6])};	// @[lab2/src/top.scala:12:18, :13:{10,17}, :17:14, :18:14, :19:14, :20:14, :21:14, :22:14, :23:14, src/main/scala/chisel3/util/Mux.scala:50:70]
  Seg seg (	// @[lab2/src/top.scala:29:19]
    .enable  (sw[8]),	// @[lab2/src/top.scala:31:25]
    .seg_in  (hotvalue),	// @[lab2/src/top.scala:12:18, src/main/scala/chisel3/util/Mux.scala:50:70]
    .seg_out (seg0)
  );
  assign ledr_0 = hotvalue[0];	// @[<stdin>:29:10, lab2/src/top.scala:12:18, :35:25, src/main/scala/chisel3/util/Mux.scala:50:70]
  assign ledr_1 = hotvalue[1];	// @[<stdin>:29:10, lab2/src/top.scala:12:18, :36:25, src/main/scala/chisel3/util/Mux.scala:50:70]
  assign ledr_2 = hotvalue[2];	// @[<stdin>:29:10, lab2/src/top.scala:12:18, :37:25, src/main/scala/chisel3/util/Mux.scala:50:70]
  assign ledr_3 = |hotvalue;	// @[<stdin>:29:10, lab2/src/top.scala:12:18, :38:30, src/main/scala/chisel3/util/Mux.scala:50:70]
endmodule

